<div class="alert alert-info">
  <h1>Session 4: Data Processing with Numpy</h1>
</div>

# NumPy

In [2]:
import numpy as np

In [4]:
lst = [1,2,3]
np.array(lst)

array([1, 2, 3])

In [5]:
mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
mat3d = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
np.array(mat3d)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
## array from range
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [114]:
list1 = [[1,2,3],['tom','jerry','jack'],[4,5,6]]
np.array(list1)

array([['1', '2', '3'],
       ['tom', 'jerry', 'jack'],
       ['4', '5', '6']], dtype='<U11')

### arange

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Zeros and Ones

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### eye 

In [26]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
mat = np.array([[1,2,3,4], [10,20,30,40], [25,35,45,55], [35,53,45,61]])
mat

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40],
       [25, 35, 45, 55],
       [35, 53, 45, 61]])

In [8]:
np.triu(mat)

array([[ 1,  2,  3,  4],
       [ 0, 20, 30, 40],
       [ 0,  0, 45, 55],
       [ 0,  0,  0, 61]])

In [9]:
np.tril(mat)

array([[ 1,  0,  0,  0],
       [10, 20,  0,  0],
       [25, 35, 45,  0],
       [35, 53, 45, 61]])

## linspace

In [27]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [30]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

## Random: creating random numbers 

In [34]:
# rand
np.random.rand(3)

array([0.92740399, 0.90733161, 0.01417881])

In [39]:
np.random.rand(3,3)

array([[0.06176005, 0.0018924 , 0.12828819],
       [0.97802688, 0.76815437, 0.8491805 ],
       [0.8661674 , 0.132174  , 0.11343509]])

In [40]:
np.random.rand(4,2)

array([[0.33607446, 0.24199298],
       [0.42935366, 0.56420807],
       [0.79329543, 0.16406123],
       [0.24599961, 0.78023906]])

In [41]:
# randn

In [42]:
np.random.randn(2)

array([-0.53377072, -0.7393743 ])

In [43]:
np.random.randn(10)

array([-0.37989306,  0.79758781,  0.22544621, -0.6931128 , -0.03672333,
        0.80499306,  0.89155266, -0.5263505 ,  0.12252094, -0.74972459])

In [48]:
nums =  np.random.randn(5)

In [49]:
nums

array([-0.42543558,  1.44723242, -0.28388417,  0.54226092, -1.3070951 ])

In [50]:
np.random.randn(3,3)

array([[ 0.24091852,  2.00384533, -1.9211516 ],
       [-1.72721918, -0.35392846, -0.00934887],
       [-1.82596714, -0.84089514,  0.15843021]])

In [51]:
#randint

In [61]:
np.random.randint(1,10)

8

In [62]:
np.random.randint(1,100,10)

array([93, 36, 68, 49,  6, 53, 86, 48, 67, 69])

In [317]:
np.random.randint(0,2, 10)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0])

In [319]:
np.random.randint(10, size = (4,3))

array([[9, 9, 7],
       [8, 7, 5],
       [4, 3, 0],
       [4, 7, 8]])

## Saving and loading

In [272]:
my_array = np.random.randint (1,100,100)

In [273]:
my_array

array([ 3, 59, 48, 24, 52, 15, 94, 21, 33, 16, 54, 96, 19,  4,  7, 88, 50,
        4, 72, 79, 44, 32, 79, 86, 18, 85, 78, 23, 29, 64, 12, 26, 57, 91,
       59, 88, 60, 93, 53, 10, 14, 35, 21, 11, 49, 81, 66, 71, 44, 62, 73,
       75, 51, 69, 79, 59, 62,  4, 89, 64, 14, 60, 67, 46, 37, 86,  2, 80,
       36, 75, 92, 91, 91, 93, 88, 36, 23, 52, 17, 72, 83, 85, 32, 73, 26,
        9, 91, 62, 82, 22, 88, 43, 18, 83, 68, 68, 19, 44, 75, 61])

In [275]:
np.save('my_array.npy', my_array)

In [278]:
a = np.load('my_array.npy')

In [279]:
a

array([ 3, 59, 48, 24, 52, 15, 94, 21, 33, 16, 54, 96, 19,  4,  7, 88, 50,
        4, 72, 79, 44, 32, 79, 86, 18, 85, 78, 23, 29, 64, 12, 26, 57, 91,
       59, 88, 60, 93, 53, 10, 14, 35, 21, 11, 49, 81, 66, 71, 44, 62, 73,
       75, 51, 69, 79, 59, 62,  4, 89, 64, 14, 60, 67, 46, 37, 86,  2, 80,
       36, 75, 92, 91, 91, 93, 88, 36, 23, 52, 17, 72, 83, 85, 32, 73, 26,
        9, 91, 62, 82, 22, 88, 43, 18, 83, 68, 68, 19, 44, 75, 61])

## Working with Arrays : Array Attributes and Methods

### reshape

In [70]:
arr = np.arange(25)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
arr2d = arr.reshape(5,5)

In [73]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
arr_random = np.random.randint(0,40,10)

In [76]:
arr_random

array([ 8, 20, 27,  3,  4, 38, 25,  7, 26, 31])

In [79]:
arr_random.reshape(2,5)

array([[ 8, 20, 27,  3,  4],
       [38, 25,  7, 26, 31]])

In [78]:
np.random.randint(0,100,15).reshape(3,5)

array([[18, 32, 45, 16, 42],
       [13, 33, 97, 28, 51],
       [ 4, 37, 55, 72, 71]])

### max,min,argmax,argmin

In [82]:
arr_random = np.random.randint(0,40,10)
arr_random

array([29, 13, 35, 18, 36, 10, 33,  6, 24, 27])

In [83]:
arr_random.max()

36

In [84]:
arr_random.min()

6

In [85]:
arr_random.argmax()

4

In [86]:
arr_random.argmin()

7

### flatten

In [88]:
arr = np.random.randn(4,4)
arr

array([[ 0.10971895,  1.5475169 , -0.57833096,  0.50039699],
       [ 0.75543361, -1.69332558, -1.15024891,  1.57016987],
       [ 1.29221685, -0.17718897, -0.71362339,  0.32597875],
       [-1.57126749, -0.11934831,  1.69432782, -0.66750767]])

In [90]:
arr.shape

(4, 4)

In [91]:
arr.flatten()

array([ 0.10971895,  1.5475169 , -0.57833096,  0.50039699,  0.75543361,
       -1.69332558, -1.15024891,  1.57016987,  1.29221685, -0.17718897,
       -0.71362339,  0.32597875, -1.57126749, -0.11934831,  1.69432782,
       -0.66750767])

In [93]:
arr.flatten().shape

(16,)

### vstack,hstack,concatenate

In [94]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [95]:
a

array([[1, 2],
       [3, 4]])

In [96]:
b

array([[5, 6],
       [7, 8]])

In [97]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [98]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [101]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [100]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### hsplit(), vsplit()

In [297]:
c = np.arange(0,25).reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [306]:
np.hsplit(c, np.array([2,3]) )

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [307]:
np.hsplit(c, np.array([3,4]) )

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [309]:
d = np.arange(0,24).reshape(6,4)

In [311]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [312]:
np.vsplit(d, 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [313]:
np.vsplit(d, np.array([1,3]))

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [314]:
# Split
np.split(c, np.array([3,4]), axis = 1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [315]:
np.split(c, np.array([3,4]), axis = 0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

### dtype attribute

In [108]:
my_arr = np.array([1,2,3,4])

In [103]:
my_arr.dtype

dtype('int32')

In [104]:
my_arr = np.array([1.5,2,3,4])

In [105]:
my_arr.dtype

dtype('float64')

In [109]:
my_arr = np.array([1,2,3,4], dtype='float64')

In [110]:
my_arr.dtype

dtype('float64')

In [111]:
my_sec_array = np.array([1.5,2.7,3.8,4,5,6],dtype = 'int32')

In [112]:
my_sec_array

array([1, 2, 3, 4, 5, 6])

# Operations

In [55]:
arr1 = np.arange(0,9).reshape(3,3)
arr2 = np.linspace(0,10,9).reshape(3,3)


In [56]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr2

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [116]:
arr1 + arr2

array([[ 0.  ,  2.25,  4.5 ],
       [ 6.75,  9.  , 11.25],
       [13.5 , 15.75, 18.  ]])

In [58]:
arr1 * arr2

array([[ 0.  ,  1.25,  5.  ],
       [11.25, 20.  , 31.25],
       [45.  , 61.25, 80.  ]])

In [59]:
arr1 / arr2

<ipython-input-59-4b2fbeb950c1>:1: RuntimeWarning: invalid value encountered in true_divide
  arr1 / arr2


array([[nan, 0.8, 0.8],
       [0.8, 0.8, 0.8],
       [0.8, 0.8, 0.8]])

Array with Scaler

In [202]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [203]:
arr + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [204]:
arr -6

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [205]:
arr +10-6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [206]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [117]:
arr = np.array([1,2,3])

In [118]:
for x in arr:
    print(x)

1
2
3


In [119]:
arr = np.array([[1,2,3],[4,5,6]])

In [120]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


## Sorting arrays

In [288]:
a = np.random.randint(4,100,20)

In [289]:
a

array([ 7, 50, 99, 34, 68, 90,  8, 74, 90, 44, 94, 77, 27, 28, 31, 26, 41,
       36, 81, 77])

In [290]:
a.sort()

In [291]:
a

array([ 7,  8, 26, 27, 28, 31, 34, 36, 41, 44, 50, 68, 74, 77, 77, 81, 90,
       90, 94, 99])

In [292]:
b = np.random.randint(4,100,20).reshape(4,5)
b

array([[79, 84, 57,  6, 30],
       [94, 58, 11, 86, 30],
       [61, 82, 80, 80, 92],
       [73, 93, 81, 64, 68]])

In [293]:
b.sort(axis= 1)

In [294]:
b

array([[ 6, 30, 57, 79, 84],
       [11, 30, 58, 86, 94],
       [61, 80, 80, 82, 92],
       [64, 68, 73, 81, 93]])

In [295]:
b.sort(axis= 0)

In [296]:
b

array([[ 6, 30, 57, 79, 84],
       [11, 30, 58, 81, 92],
       [61, 68, 73, 82, 93],
       [64, 80, 80, 86, 94]])

### Universal Array Functions

In [209]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [210]:
np.max(arr)

10

In [211]:
arr.max()

10

In [212]:
np.min(arr)

0

In [234]:
np.median(arr)

5.0

In [235]:
np.std(arr)

3.1622776601683795

In [236]:
np.append([[1,2,3],[4,5,6]], [7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
np.append([[1,2,3],[4,5,6]], [7,8,9], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [238]:
np.append([[1,2,3],[4,5,6]], [[7,8,9]], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [239]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Math Functions

In [213]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [215]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [216]:
np.exp(arr) #e^

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [217]:
np.power(arr, 3)

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [218]:
np.log(arr)

<ipython-input-218-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [219]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [220]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

### delete

In [240]:
np.delete(arr, 1)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [242]:
np.delete(arr, 3)

array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr2 = np.arange(0,25).reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [244]:
np.delete(arr2,2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [247]:
np.delete(arr2,[2,5])

array([ 0,  1,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [248]:
np.delete(arr2,[2], axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [249]:
np.delete(arr2,[2], axis = 1)

array([[ 0,  1,  3,  4],
       [ 5,  6,  8,  9],
       [10, 11, 13, 14],
       [15, 16, 18, 19],
       [20, 21, 23, 24]])

### insert

In [251]:
np.insert(arr, 2, 99)

array([ 0,  1, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.insert(arr2, 2, 99)

array([ 0,  1, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [254]:
np.insert(arr2, 2, 99, axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [99, 99, 99, 99, 99],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [260]:
np.insert(arr2, 2, 99, axis = 1)

array([[ 0,  1, 99,  2,  3,  4],
       [ 5,  6, 99,  7,  8,  9],
       [10, 11, 99, 12, 13, 14],
       [15, 16, 99, 17, 18, 19],
       [20, 21, 99, 22, 23, 24]])

In [21]:
arr3=np.insert(arr2, 2, 99, axis = 1)

In [22]:
arr3

array([[ 0,  1, 99,  2,  3,  4],
       [ 5,  6, 99,  7,  8,  9],
       [10, 11, 99, 12, 13, 14],
       [15, 16, 99, 17, 18, 19],
       [20, 21, 99, 22, 23, 24]])

In [23]:
np.delete(arr3, 2, axis = 1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
np.insert(arr3,1, [[ 11,  12, 88,  75,  33,  45]], axis = 0)

array([[ 0,  1, 99,  2,  3,  4],
       [11, 12, 88, 75, 33, 45],
       [ 5,  6, 99,  7,  8,  9],
       [10, 11, 99, 12, 13, 14],
       [15, 16, 99, 17, 18, 19],
       [20, 21, 99, 22, 23, 24]])

In [26]:
np.insert(arr3,[1], [[ 11,  12, 88,  75,  33,  45]], axis = 1)

array([[ 0, 11, 12, 88, 75, 33, 45,  1, 99,  2,  3,  4],
       [ 5, 11, 12, 88, 75, 33, 45,  6, 99,  7,  8,  9],
       [10, 11, 12, 88, 75, 33, 45, 11, 99, 12, 13, 14],
       [15, 11, 12, 88, 75, 33, 45, 16, 99, 17, 18, 19],
       [20, 11, 12, 88, 75, 33, 45, 21, 99, 22, 23, 24]])

In [28]:
np.insert(arr3,[2], [  [0], [0],  [0],  [0],  [0]], axis = 1)

array([[ 0,  1,  0, 99,  2,  3,  4],
       [ 5,  6,  0, 99,  7,  8,  9],
       [10, 11,  0, 99, 12, 13, 14],
       [15, 16,  0, 99, 17, 18, 19],
       [20, 21,  0, 99, 22, 23, 24]])

### Matrix Product   ************  **********

In [223]:
a = np.arange(1,6)
b = np.arange(2,7)
np.multiply(a,b)

array([ 2,  6, 12, 20, 30])

In [224]:
b

array([2, 3, 4, 5, 6])

In [225]:
np.matmul(a,b)

70

In [227]:
a = np.arange(0,25).reshape(5,5)
b = np.arange(1,6)

In [228]:
np.matmul(a,b)

array([ 40, 115, 190, 265, 340])

In [229]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [230]:
b

array([1, 2, 3, 4, 5])

### dot Product

In [232]:
c = np.array([1,2,3,4])
d = np.array([3,2,6,8])
np.dot(c,d)

57

## Numpy Indexing, Sclicing, and Selection

In [65]:
arr = np.arange(15,25)

In [66]:
arr

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
arr[1]

16

In [68]:
arr[8]

23

In [71]:
arr[1:5]

array([16, 17, 18, 19])

In [72]:
arr[:7]

array([15, 16, 17, 18, 19, 20, 21])

In [73]:
arr[2:]

array([17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
arr[:]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
arr[2:9:2]

array([17, 19, 21, 23])

In [76]:
arr[::2]

array([15, 17, 19, 21, 23])

In [77]:
arr[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

### Brodcasting

In [82]:
lst = [1,2,3,4,5]
lst[1:4]=10

TypeError: can only assign an iterable

In [85]:
arr4 = np.arange(0,5)

In [86]:
arr4[1:4]= 10

In [87]:
arr4

array([ 0, 10, 10, 10,  4])

In [88]:
lst[1:4] = [10,10,10]

In [89]:
lst

[1, 10, 10, 10, 5]

### copy

#### Challenge

In [90]:
a = np.arange(0,11)

In [91]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
slice_a = a[0:5]
slice_a

array([0, 1, 2, 3, 4])

In [93]:
slice_a[:] = 999

In [94]:
slice_a

array([999, 999, 999, 999, 999])

In [95]:
a

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10])

### soultion with copy

In [97]:
b = np.arange(0,11)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
b_copy = b.copy()

In [99]:
b_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
b_copy[0:5] = 999

In [101]:
b_copy

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10])

In [102]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### indexing  2D arrays (matrices)

In [103]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
mat[1]

array([20, 25, 30])

In [105]:
mat[1][2]

30

In [106]:
mat[0]

array([ 5, 10, 15])

In [109]:
mat[0][1:3]

array([10, 15])

In [111]:
mat[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [122]:
# caution
mat[0:2][1:3]

array([[20, 25, 30]])

In [127]:
mat[1:3][1]

array([35, 40, 45])

In [128]:
mat[1:3][1][2]

45

In [129]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [130]:
mat.transpose()

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [132]:
m = np.arange(0,100).reshape(10,10)

In [133]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [134]:
m[3:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [135]:
m[3:][0]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

### double slicing

In [136]:
m[3:,4:]

array([[34, 35, 36, 37, 38, 39],
       [44, 45, 46, 47, 48, 49],
       [54, 55, 56, 57, 58, 59],
       [64, 65, 66, 67, 68, 69],
       [74, 75, 76, 77, 78, 79],
       [84, 85, 86, 87, 88, 89],
       [94, 95, 96, 97, 98, 99]])

In [137]:
m[3:6,4:7]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56]])

In [138]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### <font color='red'>Fancy indexing</font>

In [146]:
m[2:8]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [147]:
m[2:8:2]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [148]:
m[[2,4,6]]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [164]:
m[[1,6]][:,1:4]

array([[11, 12, 13],
       [61, 62, 63]])

In [165]:
m[[1,6], 1:4]

array([[11, 12, 13],
       [61, 62, 63]])

In [175]:
m[[2,4],3:6]

array([[23, 24, 25],
       [43, 44, 45]])

In [174]:
m[1:3,[1,4,7]]

array([[11, 14, 17],
       [21, 24, 27]])

In [169]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
m[[1,3],[1,4,7]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [188]:
# method 1
m[[1,3]][:,[1,4,7]]

array([[11, 14, 17],
       [31, 34, 37]])

In [189]:
m[[1,3], [[1],[4],[7]]]  # not coerrect

array([[11, 31],
       [14, 34],
       [17, 37]])

In [186]:
# method 2
m[[[1], [3]], [1,4,7]]

array([[11, 14, 17],
       [31, 34, 37]])

In [187]:
# method 2
m[[1,3],:][:,[1,4,7]]

array([[11, 14, 17],
       [31, 34, 37]])

## Selection (query)

In [192]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [193]:
arr > 7

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [194]:
arr == 15

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False])

In [195]:
cond = arr>7

In [196]:
cond

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [197]:
arr[cond]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [198]:
arr[arr>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [199]:
a = 10
arr[arr == a]

array([10])

In [200]:
arr[arr <= 5]

array([1, 2, 3, 4, 5])

In [201]:
arr[arr %3 ==0]

array([ 3,  6,  9, 12, 15, 18])

## changing the values according to a criteria

In [11]:
mat = np.arange(1,26).reshape(5,5)

In [14]:
np.where(mat<10,mat,mat*10)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [15]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
np.where(mat>10,mat,mat*10)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])